---
### Settings for differnet environments, these take priority
ENVIRONMENTS:
  development:
    logfile: 'development.log'
    input:
      ESCDELAY: 250

  production:
    logfile: 'production.log'


### Regular settings, environment settings overwrite these
## Log directory, best to leave as-is. Logfiles are created / overwritten in this directory
logdir: 'log'
## Default logfile
logfile: 'default.log'

## Input settings
input:
  ## Curses ESCDELAY, in ms (default = 1000ms)
  ESCDELAY: 1000

## Text output settings
output:
  padding:        2  # Padding of text to curses window edge, left and right
  padding_height: 1  # Padding of text to curses window edges, top and bottom
  indent:         2  # Indent of continuation lines
  history_size: 100  # Amount of lines to be saved at a time

...
