---
### Settings for differnet environments, these take priority
ENVIRONMENTS:
  production:
    logfile: 'production.log'

  development:
    logfile: 'development.log'
    input:
      ESCDELAY:            100
      history_size:        100
      prompt:              '$ '
      prompt_conversation: '> '
      border_color:        'blue'
      border_attr:         'bold'

  debug:
    logfile: 'development.log'

  test:
    logfile: 'development.log'


### Regular settings, environment settings overwrite these
## Log directory, relative path from root of project
## Logfiles are created / overwritten in this directory
logdir: 'log'
## Default logfile, relative path from 'logdir' directory
logfile: 'default.log'

## Keywords that chain multiple input lines
## Can be regular expressions
chain_keywords:
  - and


## Input settings
input:
  ESCDELAY:            1000      # Curses ESCDELAY, in ms (default = 1000ms)
  history_size:        100       # Amount of input lines to save
  prompt:              '> '      # Text to place before input field
  prompt_conversation: '>> '     # Same as prompt, but in conversation mode
  border_color:        'yellow'  # Border color of Input and Command History Window,
                                 # can be Array with foreground and background colors
                                 # or string for foreground and default background color
  border_attr:         'bold'    # Also apply attribute for border

## Text output settings
output:
  padding:             3         # Padding of text to curses window edge, left and right
  padding_height:      1         # Padding of text to curses window edges, top and bottom
  indent:              2         # Indent of continuation lines
  history_size:        100       # Amount of lines to be saved at a time
  min_width:           24        # Minimum amount of width a Window has to have to be drawn
  min_height:          3         # Minimum amount of height a Window has to have to be drawn
  prompt_conversation: '=> '     # Text in front of conversation output lines

## General Menu settings
menu:
  ## Attributes for selected option
  selected_attributes:
    - 'bold'
    - 'underline'
  ## Menu navigation - selecting an option
  input:
    up:
      - 'KEY_UP'     # Up Arrow
      - 'k'
    down:
      - 'KEY_DOWN'   # Down Arrow
      - 'j'
    left:
      - 'KEY_LEFT'   # Left Arrow
      - 'h'
    right:
      - 'KEY_RIGHT'  # Right Arrow
      - 'l'
    select:          ## Select the selected option
      - 'KEY_ENTER'
      - 10           # 'KEY_ENTER' doesn't work (for me), 10 is space
      - 32           # Space Key

  ## MainMenu settings
  MainMenu:
    border_color:      'magenta'
    border_attr:       'bold'
...
