---
### Settings for differnet environments, these take priority
ENVIRONMENTS:
  development:
    logfile: 'development.log'
    input:
      ESCDELAY:    100
      history_size: 10

  debug:
    logfile: 'development.log'

  production:
    logfile: 'production.log'


### Regular settings, environment settings overwrite these
## Log directory, relative path from root of project
## Logfiles are created / overwritten in this directory
logdir: 'log'
## Default logfile, relative path from 'logdir' directory
logfile: 'default.log'

## Input settings
input:
  ESCDELAY:    1000  # Curses ESCDELAY, in ms (default = 1000ms)
  history_size: 100  # Amount of input lines to save

## Text output settings
output:
  padding:        2  # Padding of text to curses window edge, left and right
  padding_height: 1  # Padding of text to curses window edges, top and bottom
  indent:         2  # Indent of continuation lines
  history_size: 100  # Amount of lines to be saved at a time
...
